version: '2'

services:
   db:
     image: percona:latest
     volumes:
       - db_data:/var/lib/mysql
       - ./sql/employees.sql:/docker-entrypoint-initdb.d/employees.sql
       - ./sql/load_departments.dump:/docker-entrypoint-initdb.d/load_departments.dump
       - ./sql/load_employees.dump:/docker-entrypoint-initdb.d/load_employees.dump
       - ./sql/load_dept_emp.dump:/docker-entrypoint-initdb.d/load_dept_emp.dump
       - ./sql/load_dept_manager.dump:/docker-entrypoint-initdb.d/load_dept_manager.dump
       - ./sql/load_titles.dump:/docker-entrypoint-initdb.d/load_titles.dump
       - ./sql/load_salaries1.dump:/docker-entrypoint-initdb.d/load_salaries1.dump
       - ./sql/load_salaries2.dump:/docker-entrypoint-initdb.d/load_salaries2.dump
       - ./sql/load_salaries3.dump:/docker-entrypoint-initdb.d/load_salaries3.dump
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: PerceptyxToorSecret!
       MYSQL_DATABASE: employees
       MYSQL_USER: perceptyx_usr98
       MYSQL_PASSWORD: PerceptyxSecret!

   web:
     depends_on:
       - db
     image: nginx:latest
     ports:
       - "80:80"
     volumes:
       - ./code:/code
       - ./sites.conf:/etc/nginx/conf.d/default.conf
     restart: always
     links:
       - php

   php:
     image: php:7-fpm
     volumes:
       - ./code:/code
     restart: always
     environment:
       MYSQL_DATABASE: employees
       MYSQL_USER: perceptyx_usr98
       MYSQL_PASSWORD: PerceptyxSecret!
     links:
       - db

volumes:
    db_data:
