---
- name: Provisioning docker
  hosts: all
  sudo: yes
  tasks:
    - name: "Launch database container"
      docker_container:
       name: db
       image: percona:latest
       env:
           MYSQL_ROOT_PASSWORD: PerceptyxToorSecret!
           MYSQL_DATABASE: employees
           MYSQL_USER: perceptyx_usr98
           MYSQL_PASSWORD: PerceptyxSecret!
       volumes:
           - db_data:/var/lib/mysql
           - /opt/perceptyx_demo/sql/employees.sql:/docker-entrypoint-initdb.d/employees.sql
           - /opt/perceptyx_demo/sql/load_departments.dump:/docker-entrypoint-initdb.d/load_departments.dump
           - /opt/perceptyx_demo/sql/load_employees.dump:/docker-entrypoint-initdb.d/load_employees.dump
           - /opt/perceptyx_demo/sql/load_dept_emp.dump:/docker-entrypoint-initdb.d/load_dept_emp.dump
           - /opt/perceptyx_demo/sql/load_dept_manager.dump:/docker-entrypoint-initdb.d/load_dept_manager.dump
           - /opt/perceptyx_demo/sql/load_titles.dump:/docker-entrypoint-initdb.d/load_titles.dump
           - /opt/perceptyx_demo/sql/load_salaries1.dump:/docker-entrypoint-initdb.d/load_salaries1.dump
           - /opt/perceptyx_demo/sql/load_salaries2.dump:/docker-entrypoint-initdb.d/load_salaries2.dump
           - /opt/perceptyx_demo/sql/load_salaries3.dump:/docker-entrypoint-initdb.d/load_salaries3.dump
       restart_policy: always


    - name: "Launch php container"
      docker_container:
       name: php
       image: php:7-fpm
       links:
         - db
       volumes:
         - /opt/perceptyx_demo/code:/code
       env:
         MYSQL_DATABASE: employees
         MYSQL_USER: perceptyx_usr98
         MYSQL_PASSWORD: PerceptyxSecret!
       restart_policy: always

    - name: "Launch nginx container"
      docker_container:
       name: web
       image: nginx:latest
       links:
         - php
       ports:
         - 80:80
       volumes:
         - /opt/perceptyx_demo/code:/code
         - /opt/perceptyx_demo/sites.conf:/etc/nginx/conf.d/default.conf
       restart_policy: always
